import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

/// Where an IANA timezone's representative city sits.
class ZoneLocation {
  final double latitude;
  final double longitude;

  /// ISO 3166-1 alpha-2 code, used to pick a calculation method.
  final String country;

  const ZoneLocation(this.latitude, this.longitude, this.country);
}

/// IANA zone id to representative-city coordinates, read from
/// `assets/zones.json` (generated by `tool/build_zones.py` from the tz
/// database's zone.tab).
///
/// This is how the app gets a location without ever asking for the location
/// permission. The accuracy is that of the zone's representative city, which
/// is plenty for deciding which prayer window the current time falls in, but
/// can be far off for users in large single-zone countries — a user in Kashgar
/// carries `Asia/Shanghai`, some 3 hours of longitude away from Shanghai. The
/// settings override exists for exactly those users, and the tz database
/// conveniently also lists `Asia/Urumqi`.
class ZoneDirectory {
  final Map<String, ZoneLocation> _zones;

  const ZoneDirectory(this._zones);

  static Future<ZoneDirectory> load() async {
    final raw = await rootBundle.loadString('assets/zones.json');
    final json = jsonDecode(raw) as Map<String, dynamic>;
    return ZoneDirectory({
      for (final entry in json.entries)
        entry.key: ZoneLocation(
          (entry.value[0] as num).toDouble(),
          (entry.value[1] as num).toDouble(),
          entry.value[2] as String,
        ),
    });
  }

  /// Null for a zone the table doesn't know, which the caller must treat as
  /// "location unknown" rather than substituting a default.
  ZoneLocation? operator [](String? zoneId) =>
      zoneId == null ? null : _zones[zoneId];

  /// Every known zone id, sorted — the settings override lists these.
  List<String> get ids => _zones.keys.toList()..sort();
}
